module.exports = {
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  LIMIT_EXCEEDED: 'LIMIT_EXCEEDED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_IS_ALREADY_USED: 'TOKEN_IS_ALREADY_USED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  COMMON_ERROR: 'COMMON_ERROR',
  DUPLICATE_RECORD: 'DUPLICATE_RECORD',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  INVALID_SCHEMA: 'INVALID_SCHEMA',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  BAD_REQUEST: 'BAD_REQUEST'
};
